# FILE: macrotrack_api/settings.py
# PURPOSE: Django settings: installed apps, database, auth, caches, CORS, ML config.
"""
Django settings for macrotrack_api project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')

# Validate required environment variables on startup
_REQUIRED_ENV_VARS = ['SECRET_KEY', 'DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST', 'DB_PORT']
_missing_vars = [var for var in _REQUIRED_ENV_VARS if not config(var, default='')]
if _missing_vars and not DEBUG:
    raise ValueError(f"Missing required environment variables: {', '.join(_missing_vars)}")

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'simple_history',
    
    # Our apps
    'accounts',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Add this
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'macrotrack_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'macrotrack_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),

        # Connection pooling - keep connections alive for 10 minutes
        'CONN_MAX_AGE': 600,

        # Connection and query timeout settings
        'OPTIONS': {
            'connect_timeout': 10,  # 10 second connection timeout
            'options': '-c statement_timeout=30000'  # 30 second query timeout
        }
    }
}

# Django Caching Configuration
# https://docs.djangoproject.com/en/4.2/topics/cache/
# Using local memory cache for single-server deployments
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'macrotrack-cache',
        'KEY_PREFIX': 'macrotrack',
        'TIMEOUT': 3600,  # 1 hour default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
# Note: Token authentication is used instead of session-based auth.
# CSRF protection is not required for token-authenticated API endpoints
# since tokens are sent in the Authorization header, not cookies.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # ExpiringTokenAuthentication wraps DRF's TokenAuthentication and
        # rejects tokens older than TOKEN_TTL_DAYS (default 30 days).
        'accounts.authentication.ExpiringTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Token expiry: how many days before an auth token is considered expired.
# Set to None to disable expiry entirely (not recommended for production).
TOKEN_TTL_DAYS = config('TOKEN_TTL_DAYS', default=30, cast=int)

# ── HTTPS / Security Headers (enforced in production only) ───────────────────
if not DEBUG:
    SECURE_SSL_REDIRECT          = True   # redirect all HTTP → HTTPS
    SECURE_HSTS_SECONDS          = 31536000   # 1 year; tells browsers to always use HTTPS
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD          = True
    SESSION_COOKIE_SECURE        = True   # session cookie only sent over HTTPS
    CSRF_COOKIE_SECURE           = True   # CSRF cookie only sent over HTTPS
    SECURE_BROWSER_XSS_FILTER    = True
    SECURE_CONTENT_TYPE_NOSNIFF  = True
    X_FRAME_OPTIONS              = 'DENY'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    config('CORS_ORIGIN', default='http://localhost:3000'),
]

CORS_ALLOW_CREDENTIALS = True
AUTH_USER_MODEL = 'accounts.User'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
]

# Google OAuth Configuration
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default=None)
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET', default=None)

# Email Configuration
# For development: Use console backend (prints emails to console)
# For production: Configure SMTP settings in .env file
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@macrotrack.com')

# Frontend URL for password reset links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# STATIC FILES CONFIGURATION (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional locations of static files
STATICFILES_DIRS = []

# Use WhiteNoise for serving static files in production
# Install: pip install whitenoise
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

    # Add WhiteNoise middleware (must be after SecurityMiddleware)
    MIDDLEWARE.insert(
        MIDDLEWARE.index('django.middleware.security.SecurityMiddleware') + 1,
        'whitenoise.middleware.WhiteNoiseMiddleware',
    )

# MEDIA FILES CONFIGURATION (User Uploaded Files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB

# LOGGING CONFIGURATION
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',  # Changed from RotatingFileHandler to avoid Windows file locking issues
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',  # Changed from RotatingFileHandler to avoid Windows file locking issues
            'filename': BASE_DIR / 'logs' / 'security.log',
            'formatter': 'verbose',
        },
        'db_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',  # Changed from RotatingFileHandler to avoid Windows file locking issues
            'filename': BASE_DIR / 'logs' / 'db_queries.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['db_file'],
            'level': 'DEBUG' if DEBUG else 'WARNING',  # Only log slow queries in production
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
import os
log_dir = BASE_DIR / 'logs'
if not os.path.exists(log_dir):
    os.makedirs(log_dir)

# SESSION CONFIGURATION
# Session security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 1209600  # 2 weeks

# CSRF security
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [config('CORS_ORIGIN', default='http://localhost:3000')]

# DATABASE CONNECTION POOLING (Optional but recommended)
# For production, consider using:
# - pgbouncer for PostgreSQL connection pooling
# - Or django-db-connection-pool package

# AGE VERIFICATION AND SAFETY SETTINGS
# Minimum age requirement (COPPA compliance)
MINIMUM_USER_AGE = config('MINIMUM_USER_AGE', default=13, cast=int)

# Enable eating disorder warnings
ENABLE_EATING_DISORDER_WARNINGS = config('ENABLE_EATING_DISORDER_WARNINGS', default=True, cast=bool)

# Minimum safe calorie targets
MINIMUM_CALORIES_MALE = config('MINIMUM_CALORIES_MALE', default=1500, cast=int)
MINIMUM_CALORIES_FEMALE = config('MINIMUM_CALORIES_FEMALE', default=1200, cast=int)

# Maximum safe weight loss rate (kg/week)
MAX_SAFE_WEIGHT_LOSS_RATE = config('MAX_SAFE_WEIGHT_LOSS_RATE', default=1.0, cast=float) # Reload trigger

# Energy equivalent used when estimating TDEE from weight change
# (approximate kcal stored per kg of body weight change)
CALORIES_PER_KG_BODY_WEIGHT = config('CALORIES_PER_KG_BODY_WEIGHT', default=7700, cast=int)

# ── Email configuration guard ─────────────────────────────────────────────────
# In production, if the email backend is SMTP but no credentials are configured,
# OTP verification and password reset will silently fail. Warn loudly at startup.
import warnings as _warnings
_using_smtp = 'smtp' in EMAIL_BACKEND.lower()
_missing_email_creds = not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD
if not DEBUG and _using_smtp and _missing_email_creds:
    _warnings.warn(
        "EMAIL_HOST_USER and EMAIL_HOST_PASSWORD are not set but EMAIL_BACKEND is SMTP. "
        "OTP emails will fail in production. Set EMAIL_HOST_USER and EMAIL_HOST_PASSWORD in .env.",
        RuntimeWarning,
        stacklevel=2,
    )