# Generated by Django 4.2 on 2025-12-06 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fdc_id', models.IntegerField(blank=True, help_text='USDA FoodData Central ID', null=True, unique=True)),
                ('source', models.CharField(choices=[('usda', 'USDA Database'), ('custom', 'Custom User Entry')], default='usda', max_length=10)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('serving_description', models.CharField(default='100g', max_length=200)),
                ('is_verified', models.BooleanField(default=False, help_text='True for USDA foods or admin-verified custom foods')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_count', models.IntegerField(default=0, help_text='Track popularity for cache management')),
                ('created_by', models.ForeignKey(blank=True, help_text='Only set for custom foods', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-search_count', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['fdc_id'], name='api_food_fdc_id_893ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='api_food_name_a88702_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['source', 'is_verified'], name='api_food_source_ffb6d6_idx'),
        ),
    ]
