# Generated by Django 4.2 on 2025-12-06 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=20)),
                ('date', models.DateField(help_text='Date when the meal was consumed')),
                ('time', models.TimeField(blank=True, help_text='Time when the meal was consumed', null=True)),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_carbs', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_fat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who logged this meal', on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.DecimalField(decimal_places=2, default=1, help_text='Number of servings (e.g., 1.5)', max_digits=8)),
                ('serving_unit', models.CharField(default='serving', help_text='Unit of measurement (serving, grams, oz, cup, etc.)', max_length=50)),
                ('serving_grams', models.DecimalField(decimal_places=2, default=100, help_text='Grams per serving unit', max_digits=8)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(help_text='The food item', on_delete=django.db.models.deletion.CASCADE, related_name='meal_foods', to='api.food')),
                ('meal', models.ForeignKey(help_text='The meal this food belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='meal_foods', to='api.meal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['user', 'date'], name='api_meal_user_id_be123e_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['user', 'meal_type'], name='api_meal_user_id_f203aa_idx'),
        ),
    ]
