# Generated by Django 4.2 on 2025-12-06 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_meal_mealfood_meal_api_meal_user_id_be123e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5)),
                ('date', models.DateField(help_text='Date of weight measurement')),
                ('notes', models.TextField(blank=True, help_text='Optional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who logged this weight', on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='weightlog',
            index=models.Index(fields=['user', 'date'], name='api_weightl_user_id_5416a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weightlog',
            unique_together={('user', 'date')},
        ),
    ]
