# Generated by Django 4.2 on 2025-12-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weightlog_weightlog_api_weightl_user_id_5416a5_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category'], name='api_food_categor_a068cd_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['search_count'], name='api_food_search__bea35a_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['-search_count', '-created_at'], name='api_food_search__57e5c4_idx'),
        ),
    ]
