# Generated by Django 4.2 on 2025-12-13 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_food_api_food_categor_a068cd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='food',
            name='api_food_categor_a068cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='food',
            name='api_food_search__bea35a_idx',
        ),
        migrations.RemoveIndex(
            model_name='food',
            name='api_food_search__57e5c4_idx',
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Calories cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Carbs cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Fat cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='food',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0, message='Fiber cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Protein cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Calories cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Carbs cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Fat cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Protein cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='serving_grams',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Grams per serving unit', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, message='Serving grams must be greater than 0')]),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Number of servings (e.g., 1.5)', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, message='Serving size must be greater than 0')]),
        ),
    ]
