# Generated by Django 4.2.7 on 2025-12-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_food_api_food_categor_a068cd_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='weightlog',
            index=models.Index(fields=['user'], name='api_weightl_user_id_84fdc6_idx'),
        ),
    ]
