# Generated by Django 4.2.7 on 2025-12-28 10:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_add_weightlog_user_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_serving_size', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('last_serving_unit', models.CharField(default='serving', max_length=50)),
                ('last_serving_grams', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('last_logged', models.DateTimeField(auto_now=True, help_text='Last time this food was logged')),
                ('times_logged', models.IntegerField(default=1, help_text='Total times logged')),
                ('food', models.ForeignKey(help_text='Recently logged food', on_delete=django.db.models.deletion.CASCADE, related_name='recent_for_users', to='api.food')),
                ('user', models.ForeignKey(help_text='User who logged this food', on_delete=django.db.models.deletion.CASCADE, related_name='recent_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recent foods',
                'ordering': ['-last_logged'],
                'indexes': [models.Index(fields=['user', '-last_logged'], name='api_recentf_user_id_684854_idx')],
                'unique_together': {('user', 'food')},
            },
        ),
        migrations.CreateModel(
            name='FoodImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded food image', upload_to='food_images/%Y/%m/%d/')),
                ('detection_results', models.JSONField(help_text='Full YOLO+CLIP output including bounding boxes, confidence scores')),
                ('detected_items', models.JSONField(help_text='Simplified list of detected food items with nutrition')),
                ('total_items_detected', models.IntegerField(default=0, help_text='Number of food items detected')),
                ('confidence_avg', models.FloatField(blank=True, help_text='Average confidence score across all detections', null=True)),
                ('processing_time', models.FloatField(help_text='Time taken to process image in seconds')),
                ('user_verified', models.BooleanField(default=False, help_text='Whether user confirmed the detection was accurate')),
                ('user_corrections', models.JSONField(blank=True, help_text='User corrections to AI predictions', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_meal', models.ForeignKey(blank=True, help_text='Meal created from this image analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_image_analysis', to='api.meal')),
                ('user', models.ForeignKey(help_text='User who uploaded this image', on_delete=django.db.models.deletion.CASCADE, related_name='image_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Food image analyses',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', '-uploaded_at'], name='api_foodima_user_id_ef9193_idx'), models.Index(fields=['user_verified'], name='api_foodima_user_ve_51ec80_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_serving_size', models.DecimalField(decimal_places=2, default=1, help_text="User's preferred serving size", max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('default_serving_unit', models.CharField(default='serving', help_text="User's preferred serving unit", max_length=50)),
                ('default_serving_grams', models.DecimalField(decimal_places=2, default=100, help_text='Grams per serving unit', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('times_used', models.IntegerField(default=0, help_text='Number of times logged from favorites')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Last time this favorite was used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(help_text='The favorited food item', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.food')),
                ('user', models.ForeignKey(help_text='User who favorited this food', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-times_used', '-last_used'],
                'indexes': [models.Index(fields=['user', '-times_used'], name='api_favorit_user_id_69d2bd_idx'), models.Index(fields=['user', '-last_used'], name='api_favorit_user_id_cd8f90_idx')],
                'unique_together': {('user', 'food')},
            },
        ),
    ]
