# Generated by Django 4.2.7 on 2025-12-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_recentfood_foodimageanalysis_favoritefood'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recentfood',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recentfood',
            name='food',
        ),
        migrations.RemoveField(
            model_name='recentfood',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteFood',
        ),
        migrations.DeleteModel(
            name='RecentFood',
        ),
    ]
