# Generated by Django 4.2.7 on 2025-12-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_recentfood_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['user', '-date', '-time'], name='api_meal_user_id_f8e897_idx'),
        ),
        migrations.AddIndex(
            model_name='mealfood',
            index=models.Index(fields=['meal'], name='api_mealfoo_meal_id_eda19e_idx'),
        ),
        migrations.AddIndex(
            model_name='mealfood',
            index=models.Index(fields=['food'], name='api_mealfoo_food_id_864057_idx'),
        ),
        migrations.AddIndex(
            model_name='mealfood',
            index=models.Index(fields=['meal', 'created_at'], name='api_mealfoo_meal_id_5ca850_idx'),
        ),
    ]
