# Generated by Django 4.2.7 on 2026-01-01 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_meal_api_meal_user_id_f8e897_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for the note')),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of selected tags (e.g., 'Traveling', 'Sick')")),
                ('note_text', models.TextField(blank=True, help_text='Additional context/journaling', null=True)),
                ('activity_level', models.CharField(choices=[('rest', 'Rest day'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active')], default='moderate', help_text='General activity level for the day', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this note', on_delete=django.db.models.deletion.CASCADE, related_name='daily_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='api_dailyno_user_id_d7154d_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
