# Generated by Django 4.2.7 on 2026-01-03 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_dailynote'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the check-in')),
                ('weight_at_checkin', models.DecimalField(blank=True, decimal_places=2, help_text="User's weight at check-in time", max_digits=5, null=True)),
                ('calorie_target_before', models.IntegerField(help_text='Calorie target before any adjustment')),
                ('calorie_target_after', models.IntegerField(help_text='Calorie target after adjustment (may be same as before)')),
                ('reflection', models.CharField(blank=True, choices=[('great', 'Great'), ('okay', 'Okay'), ('struggled', 'Struggled')], help_text='How the user felt about their week', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from the user', null=True)),
                ('accepted_adjustment', models.BooleanField(default=False, help_text='Whether user accepted the calorie adjustment')),
                ('goal_changed', models.BooleanField(default=False, help_text='Whether user changed their goal during check-in')),
                ('rate_changed', models.BooleanField(default=False, help_text='Whether user changed their rate preference')),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Weight change rate (kg/week) at check-in', max_digits=4, null=True)),
                ('adherence_percent', models.DecimalField(blank=True, decimal_places=1, help_text='Calorie adherence percentage at check-in', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who completed this check-in', on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='api_userche_user_id_ba3826_idx')],
            },
        ),
    ]
