# Generated by Django 4.2.7 on 2026-01-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_usercheckin_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='Food category (protein, grains, vegetables, fruits, nuts, dairy)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fdc_id',
            field=models.CharField(blank=True, help_text='External API ID (USDA FoodData Central ID or FatSecret food_id)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='source',
            field=models.CharField(choices=[('usda', 'USDA Database'), ('fatsecret', 'FatSecret Database'), ('custom', 'Custom User Entry')], default='usda', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together={('fdc_id', 'source')},
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['source', 'category'], name='api_food_source_2400e0_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category', '-search_count'], name='api_food_categor_fafa65_idx'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(check=models.Q(('fdc_id__isnull', True), models.Q(('fdc_id', ''), _negated=True), _connector='OR'), name='food_fdc_id_not_empty'),
        ),
    ]
