# Generated by Django 4.2.7 on 2026-01-30 10:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_improve_food_model_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFood',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('fdc_id', models.CharField(blank=True, help_text='External API ID (USDA FoodData Central ID or FatSecret food_id)', max_length=100, null=True)),
                ('source', models.CharField(choices=[('usda', 'USDA Database'), ('fatsecret', 'FatSecret Database'), ('custom', 'Custom User Entry')], default='usda', max_length=10)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Calories cannot be negative')])),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Protein cannot be negative')])),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Carbs cannot be negative')])),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Fat cannot be negative')])),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0, message='Fiber cannot be negative')])),
                ('category', models.CharField(blank=True, db_index=True, help_text='Food category (protein, grains, vegetables, fruits, nuts, dairy)', max_length=200, null=True)),
                ('serving_description', models.CharField(default='100g', max_length=200)),
                ('is_verified', models.BooleanField(default=False, help_text='True for USDA foods or admin-verified custom foods')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('search_count', models.IntegerField(default=0, help_text='Track popularity for cache management')),
                ('is_archived', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical food',
                'verbose_name_plural': 'historical foods',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=20)),
                ('date', models.DateField(help_text='Date when the meal was consumed')),
                ('time', models.TimeField(blank=True, help_text='Time when the meal was consumed', null=True)),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_carbs', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_fat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical meal',
                'verbose_name_plural': 'historical meals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='food',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodimageanalysis',
            name='image_expires_at',
            field=models.DateTimeField(default='2026-06-01T00:00:00+00:00'),
        ),
        migrations.AlterField(
            model_name='weightlog',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5, validators=[django.core.validators.MinValueValidator(20, message='Weight must be at least 20 kg'), django.core.validators.MaxValueValidator(500, message='Weight cannot exceed 500 kg')]),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['is_archived', 'search_count'], name='api_food_is_arch_0f613d_idx'),
        ),
        migrations.AddIndex(
            model_name='foodimageanalysis',
            index=models.Index(fields=['image_expires_at'], name='api_foodima_image_e_9a5f69_idx'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'meal_type'), name='unique_meal_per_day'),
        ),
        migrations.AddField(
            model_name='historicalmeal',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmeal',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who logged this meal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfood',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Only set for custom foods', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfood',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
