# Generated by Django 4.2.7 on 2026-01-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_historicalfood_historicalmeal_food_is_archived_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['is_verified', 'category', 'name'], name='api_food_is_veri_18da00_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['user', 'date', 'total_calories'], name='api_meal_user_id_1a1ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='usercheckin',
            index=models.Index(fields=['user', '-date', 'weekly_rate'], name='api_userche_user_id_c27104_idx'),
        ),
        migrations.AddIndex(
            model_name='usercheckin',
            index=models.Index(fields=['user', 'accepted_adjustment'], name='api_userche_user_id_2c6762_idx'),
        ),
        migrations.AddIndex(
            model_name='weightlog',
            index=models.Index(fields=['user', 'date', 'weight'], name='api_weightl_user_id_7b103b_idx'),
        ),
    ]
