# Generated by Django 4.2.7 on 2026-03-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_performance_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mealfood',
            constraint=models.CheckConstraint(check=models.Q(('serving_grams__gt', 0)), name='mealfood_serving_grams_positive'),
        ),
        migrations.AddConstraint(
            model_name='mealfood',
            constraint=models.CheckConstraint(check=models.Q(('serving_size__gt', 0)), name='mealfood_serving_size_positive'),
        ),
    ]
