# Generated by Django 4.2.7 on 2026-03-09 13:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_add_fiber_exerciselog_recipe'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exerciselog',
            new_name='api_exercis_user_id_7efddb_idx',
            old_name='api_exerciselog_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='exerciselog',
            new_name='api_exercis_user_id_d5194c_idx',
            old_name='api_exerciselog_user_date_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='recipe',
            new_name='api_recipe_user_id_0f36cb_idx',
            old_name='api_recipe_user_idx',
        ),
        migrations.RenameIndex(
            model_name='recipe',
            new_name='api_recipe_user_id_386802_idx',
            old_name='api_recipe_user_name_idx',
        ),
        migrations.AddField(
            model_name='historicalmeal',
            name='total_fiber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='calories_burned',
            field=models.DecimalField(decimal_places=2, help_text='Estimated calories burned', max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Calories burned cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateField(help_text='Date when the exercise was performed'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Duration of exercise in minutes', validators=[django.core.validators.MinValueValidator(1, message='Duration must be at least 1 minute')]),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise_name',
            field=models.CharField(help_text='Name of the exercise activity', max_length=200),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about the exercise', null=True),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='user',
            field=models.ForeignKey(help_text='User who logged this exercise', on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0, message='Fiber cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Calories cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Carbs cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or instructions', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Fat cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0, message='Fiber cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Recipe name', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='Protein cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_description',
            field=models.CharField(default='1 serving', help_text='Description of what one serving is', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(help_text='User who created this recipe', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
