# Generated by Django 4.2.7 on 2026-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_api_exerciselog_user_date_idx_api_exercis_user_id_7efddb_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['is_verified'], name='api_food_is_veri_81a4a2_idx'),
        ),
    ]
