# Generated by Django 4.2.7 on 2026-03-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_water_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fdc_id',
            field=models.CharField(blank=True, help_text='External API ID (FatSecret food_id)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='source',
            field=models.CharField(choices=[('fatsecret', 'FatSecret Database'), ('custom', 'Custom User Entry')], default='fatsecret', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfood',
            name='fdc_id',
            field=models.CharField(blank=True, help_text='External API ID (FatSecret food_id)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfood',
            name='source',
            field=models.CharField(choices=[('fatsecret', 'FatSecret Database'), ('custom', 'Custom User Entry')], default='fatsecret', max_length=10),
        ),
    ]
