# Generated by Django 4.2.7 on 2026-04-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_food_fdc_id_alter_food_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealfood',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI')], default='manual', help_text='How this food was added: manually via search or via AI image analysis', max_length=10),
        ),
    ]
