# Generated by Django 4.2.7 on 2026-06-01 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_usercheckin_unique_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlog',
            name='amount_ml',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
