# Generated by Django 4.2.7 on 2025-12-28 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_auth_provider_user_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', help_text='Preferred unit for weight display', max_length=10)),
                ('height_unit', models.CharField(choices=[('cm', 'Centimeters'), ('ft', 'Feet/Inches')], default='cm', help_text='Preferred unit for height display', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='light', help_text='UI theme preference', max_length=20)),
                ('show_fiber', models.BooleanField(default=True, help_text='Show fiber in nutrition details')),
                ('show_saturated_fat', models.BooleanField(default=False, help_text='Show saturated fat breakdown')),
                ('show_micronutrients', models.BooleanField(default=False, help_text='Show vitamins and minerals')),
                ('dashboard_view', models.CharField(choices=[('daily', 'Daily View'), ('weekly', 'Weekly View'), ('monthly', 'Monthly View')], default='daily', help_text='Default dashboard view', max_length=20)),
                ('profile_public', models.BooleanField(default=False, help_text='Make profile visible to other users')),
                ('show_weight_progress', models.BooleanField(default=True, help_text='Display weight progress charts')),
                ('auto_save_image_detections', models.BooleanField(default=False, help_text='Automatically save AI-detected foods to diary')),
                ('image_detection_confidence_threshold', models.FloatField(default=0.15, help_text='Minimum confidence for AI food detection (0.0-1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User settings',
            },
        ),
    ]
