# Generated by Django 4.2.7 on 2025-12-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
