# Generated by Django - Migration for legal consent and encryption fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age verification', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False, help_text='User accepted privacy policy'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy_accepted_date',
            field=models.DateTimeField(blank=True, help_text='When privacy policy was accepted', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='User accepted terms of service'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_date',
            field=models.DateTimeField(blank=True, help_text='When terms were accepted', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parental_consent_provided',
            field=models.BooleanField(default=False, help_text='For users under 18'),
        ),
    ]
