# Generated by Django 4.2.7 on 2026-01-30 10:35

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_update_user_model_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.TextField(db_index=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth for age verification', null=True)),
                ('age', models.IntegerField(blank=True, help_text='Deprecated: Calculate from date_of_birth instead', null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Deprecated: Use WeightLog model for current weight', null=True)),
                ('goal_weight', models.FloatField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, max_length=20, null=True)),
                ('goal', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.CharField(blank=True, max_length=20, null=True)),
                ('calorie_target', models.IntegerField(blank=True, null=True)),
                ('protein_target', models.IntegerField(blank=True, null=True)),
                ('carbs_target', models.IntegerField(blank=True, null=True)),
                ('fat_target', models.IntegerField(blank=True, null=True)),
                ('macro_preset', models.CharField(blank=True, default='balanced', max_length=20, null=True)),
                ('google_id', models.TextField(blank=True, db_index=True, null=True)),
                ('auth_provider', models.CharField(blank=True, default='email', max_length=20, null=True)),
                ('privacy_policy_accepted', models.BooleanField(default=False, help_text='User accepted privacy policy')),
                ('privacy_policy_accepted_date', models.DateTimeField(blank=True, help_text='When privacy policy was accepted', null=True)),
                ('terms_accepted', models.BooleanField(default=False, help_text='User accepted terms of service')),
                ('terms_accepted_date', models.DateTimeField(blank=True, help_text='When terms were accepted', null=True)),
                ('parental_consent_provided', models.BooleanField(default=False, help_text='For users under 18')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'email'], name='accounts_us_is_dele_9d7ff7_idx'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
