# Generated by Django 4.2.7 on 2026-03-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='email_hmac',
            field=models.CharField(blank=True, db_index=True, help_text='HMAC-SHA256 of lowercased email — used for fast indexed lookups', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_hmac',
            field=models.CharField(blank=True, db_index=True, help_text='HMAC-SHA256 of lowercased email — used for fast indexed lookups', max_length=64, null=True, unique=True),
        ),
    ]
