# Generated by Django 4.2.7 on 2026-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_fiber_target'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_of_birth'], name='accounts_us_date_of_b40948_idx'),
        ),
    ]
