# Generated by Django 4.2.7 on 2026-04-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationotp',
            name='otp_hash',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='email_hmac',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='otp_hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_hmac',
        ),
        migrations.AddField(
            model_name='emailverificationotp',
            name='otp',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='otp',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='privacy_policy_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='terms_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='privacy_policy_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
