# Generated by Django 4.2.7 on 2026-05-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_managers_historicaluser_checkin_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='goal_set_date',
            field=models.DateField(blank=True, help_text='Date the current goal was set; used to reset the progress bar', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_set_date',
            field=models.DateField(blank=True, help_text='Date the current goal was set; used to reset the progress bar', null=True),
        ),
    ]
